
<!DOCTYPE html>
<!--[if lt IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]>
<html lang="ru" class="lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]>
<html lang="ru" class="lt-ie9"><![endif]-->
<!--[if gt IE 8]><!-->
<html lang="ru">
<!--<![endif]-->
<head>

    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="/css/captcha.css"/>

</head>
<body>



<a href="/">Вернуться на главную страницу</a>

<?= $admin_list ?>

<?= $edit_form ?>

<?= $admin_options ?>

<?= $users_result_list ?>

<?= $users_result_details_list ?>

<?php global $modx_data;
//Debugger::PrintR($modx_data);

?>

</body>